### ISSUE TITLE
`Bytes.or` calls `Bytes.and`

### ISSUE THREAD

**Issue by jbaiter** [patrickfav/bytes-java#2]
https://github.com/patrickfav/bytes-java/blob/abdd852513f2d49aab5498dc81dc58c9baca898d/src/main/java/at/favre/lib/bytes/Bytes.java#L746-L748

This should probably be this, non?

```java
    public Bytes or(Bytes bytes) {
        return or(bytes.internalArray());
    }
```

**Comment by patrickfav** [comment]
Absolutely correct. Unfortunatly I had poor tests and did not catch it. Thanks, will be release in 0.5.0
