### ISSUE TITLE
Crashes on Android API level < 19

### ISSUE THREAD

**Issue by vanosidor** [patrickfav/bytes-java#33]
Exception in method Bytes(Objects.requireNonNull(array, "passed array must not be null"),byteOrder) java.lang.NoClassDefFoundError: java.util.Objects.

**Comment by patrickfav** [comment]
Hi,

Thanks for the report. As stated in the README, this is a Java 7 project. Unfortunately Java 7 is only fully supported from SDK 19+, see https://stackoverflow.com/a/22303654/774398

It seems only SDK 19 back-ported `Objects.requireNonNull`. Not much that can be done. AFAIK even Google is dropping support for devices < SDK 19
