### ISSUE TITLE
Bytes.bitAt assumes big endian byte order

### ISSUE THREAD

**Issue by gfpeltier** [patrickfav/bytes-java#39]
Hello! Thank you for this library. It is exactly what I was looking for. However, I was playing around with it and it appears the `bitAt(int index)` method always assumes the underlying buffer byte order is big endian. This is problematic when the underlying byte order is little endian. For example:

```java
byte[] barr = new byte[]{1, 0, 0, 0};
Bytes bytes = Bytes.wrap(barr).byteOrder(ByteOrder.LITTLE_ENDIAN);
bytes.byteAt(0);   // 1
bytes.intAt(0);    // 1
bytes.bitAt(0);    // false
```

**Comment by patrickfav** [comment]
I will release that in the next couple of days.
