### ISSUE TITLE
Bitwise OR calls bitwise AND internally

### ISSUE THREAD

**Issue by ioreskovic** [patrickfav/bytes-java#5]
https://github.com/patrickfav/bytes-java/blob/53187bea8485cd6a717bbb6ea6df1808316e8661/src/main/java/at/favre/lib/bytes/Bytes.java#L710

**Comment by patrickfav** [comment]
Hi Ivan, thanks for the report.

This is a duplicate of #2 and will be release 0.5.0 shortly.
